### ISSUE TITLE
Windows install guide says to press down S2 for Rescue Mode

### ISSUE THREAD

**Issue by geslotencirkel** [axoloti/axoloti#196]
http://community.axoloti.com/t/installing-on-windows/36

"Enter rescue mode, either by:
power down the board, press S2, power up the board"

I believe this should say S1 - like the error in the Axoloti UI
"No devices in DFU mode detected. To bring Axoloti Core in DFU mode, remove power from Axoloti Core, and power it up while holding button S1."

**Comment by TheTechnobear** [comment]
fixed, thanks @JohannesTaelman , can close
