### ISSUE TITLE
Installation on debian: no axoloti_rutime folder

### ISSUE THREAD

**Issue by JorenSix** [axoloti/axoloti#203]
Hi,

After installing axoloti 1.0.2 on debian 8.1 with `sudo dpkg -i axoloti-linux-1.0.2.deb` the gui complains about the fact that there is no `~/axoloti_runtime` folder. Subsequently the script  to fix the usb device permissions (the udev rules, mentioned here: http://community.axoloti.com/t/installing-on-linux/56) is nowhere to be found. 

I did find the script in the source release (axo_runtime_linux_1.0.2.tgz) and everything went smoothly after running it.

**Comment by TheTechnobear** [comment]
Did you unpack  the runtime zip as per installation guide ...

**Comment by JorenSix** [comment]
Hmm that could be the problem indeed ;) Somehow i skipped that step.
