### ISSUE TITLE
small detail in Axoloti User guide - sub-unit adjustment shortcuts

### ISSUE THREAD

**Issue by geslotencirkel** [axoloti/axoloti#211]
Hi - in the axoloti user guide http://community.axoloti.com/t/axoloti-user-guide/50 there is a note about Parameter changing. I am not sure if all changes are at a fixed increment amount (mouse only: .5 ; shift-mouse: .05) but there is also another level of precision: shift-ctrl-mouse (which adjusts by .01)

**Comment by TheTechnobear** [comment]
thanks, updated
