### ISSUE TITLE
FW/HW:Inserting SD card caused voltage fluctuations.

### ISSUE THREAD

**Issue by TheTechnobear** [axoloti/axoloti#221]
(prototype v0.5 board)

with or without an SD Card inserted by VDD displayed = 3.28v
however, if I start board without and SD Card, and insert it whilst its running.
VDD voltage wildly fluctuates between 3.00v and 3.4v , and never appears to stabilise.

**Comment by JohannesTaelman** [comment]
prototype v0.5 issue, not in production v1.0
