### ISSUE TITLE
typo in platform_linux/upload_fw_dfu.sh

### ISSUE THREAD

**Issue by pierstitus** [axoloti/axoloti#223]
dfu upload script for linux doesn't work, there is /bin on two places, the second should be removed.

    cd "${platformdir}/bin"
    ./bin/dfu-util ...

**Comment by TheTechnobear** [comment]
k, i'll fix now

**Comment by TheTechnobear** [comment]
are you using the latest version (either from repo, the latest axoloti_runtime... ?

**Comment by TheTechnobear** [comment]
my bad, it was only recently broken... fixing now

**Comment by TheTechnobear** [comment]
fixed, will need need users to take a new axoloti_runtime version (linux only)

**Comment by TheTechnobear** [comment]
@pierstitus just as an 'aside'  (as this needed fixing) , there is no real reason to use dfu update on an axoloti board, except in failure cases. (perhaps discovery board?)

**Comment by pierstitus** [comment]
My beta version didn't connect, probably old firmware or I broke something when trying some things, so I had to use the rescue flash option.
