### ISSUE TITLE
FW: flashing via memory fails

### ISSUE THREAD

**Issue by TheTechnobear** [axoloti/axoloti#233]
sometimes when flashing new firmware when non in DFU, it will fail and both LEDs will be lit.
(this is on both V1 and V0.5 boards)

the UI reports everything is done correctly (e.g. write) 

but the board immediately lights both LEDS.
i.e. on the first batch of slow flashes
(rather than later faster flashing)

its not every time, but happens around 1 in 10?  not sure if random, or if its after board has been connected/used etc.

**Comment by axoloti** [comment]
addressed in 3f12c30426be5e013a65b412f88fd482a0a78295
