### ISSUE TITLE
table read/delay read in poly sub patch fails to compile

### ISSUE THREAD

**Issue by TheTechnobear** [axoloti/axoloti#236]
dsp code is expecting to be in parent->common (because an attribute?), but the table is allocated as a normal instance (correctly I think)

**Comment by geslotencirkel** [comment]
Putting the table in main object and referencing it from a polyphonic subobject causes disconnect crash.

**Comment by TheTechnobear** [comment]
@geslotencirkel . not here it doesnt... can you provide an example?
(post it on the forum, and then crosslink here, as github wont allow axp uploads)
see my post here, of a poly sub patch working when accessing parent table
http://community.axoloti.com/t/can-tables-be-used-in-subpatches-in-polyphonic-mode/312/16?u=thetechnobear

**Comment by geslotencirkel** [comment]
Sorry it was related to "Keyb mod" !

**Comment by JohannesTaelman** [comment]
making progress on this, stay tuned
