### ISSUE TITLE
Instructions for Compiling from Source on windows have a mistake

### ISSUE THREAD

**Issue by geslotencirkel** [axoloti/axoloti#253]
/doc/compiling from source on windows.html references a get dependencies .bat file that isn't found in the platform_win directory

**Comment by geslotencirkel** [comment]
http://community.axoloti.com/t/installing-on-windows/36 obviously is more upto date than the bundled files at this point.

**Comment by axoloti** [comment]
fixed in commit 1d64bdcb23f3d4e6a09c57e7f510f3cd7f1f8b3f
