### ISSUE TITLE
Midi intern cc bad conversion

### ISSUE THREAD

**Issue by GaoTamanrasset** [axoloti/axoloti#391]
Hi,

I think there are a bug in midi/intern/cc object in k-rate code : 

if ((inlet_trig>0) && !ntrig) {PatchMidiInHandler(MIDI_DEVICE_INTERNAL, 0,MIDI_CONTROL_CHANGE + (attr_channel-1),attr_cc,__USAT(inlet_v>>20,7));  ntrig=1;}

__USAT(inlet_v>>21,7) seems to be better.

[midi_intern_bug.axp.zip](https://github.com/axoloti/axoloti/files/859643/midi_intern_bug.axp.zip)

**Comment by TheTechnobear** [comment]
20 bit shift is correct, your proposed change would lead to values being half what they should be.

Ive also tested with my own patch and behaviour is as expected/correct. (attached screenshot) 

(sorry, didnt have time to look at your patch) 

![screen shot 2017-05-10 at 14 21 27](https://cloud.githubusercontent.com/assets/4019664/25898421/5f9e9648-358c-11e7-8197-dc571d8186be.png)
