### ISSUE TITLE
Axoloti Patcher crashes when viewing the settings of a subpatch.

### ISSUE THREAD

**Issue by vormplus** [axoloti/axoloti#439]
Found a bug that is blocking for me when working with subpatches.

### How to replicate

1. Create a new patch.
2. Add a patch/patcher object.
3. Open the subpatch.
4. Go to View > Settings.
5. Axoloti Patcher crashes.

I'm running macOS 10.13.6, Axoloti 1.0.12.

**Comment by TheTechnobear** [comment]
I don't get this with macOS 10.14, axoloti 1.0.12

Id 'guess' its probably more to do with JVM version rather than macOS?
what JVM are you currently on?

**Comment by vormplus** [comment]
That must have been it. Just recently updated to 10.13 but my Java install was still behind. Works as it should now. Thanks.
